version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    container_name: metagame-frontend
    ports:
      - "3000:3000"
    command: sh -c "npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    container_name: metagame-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SECRET_KEY=super-secret-key
    command: sh -c "/wait && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: metagame-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metagame
      POSTGRES_USER: metagame_user
      POSTGRES_PASSWORD: metagame_password
      PGDATA: /var/lib/postgresql/data/pgdata  # Évite la réinitialisation des données
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metagame_user -d metagame"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

